name: "Terraform Infrastructure Change Management Pipeline with GitHub Actions"

on: push

jobs:
  terraform:
    name: "Terraform Infrastructure Change Management"
    runs-on: [self-hosted, linux, gke-runner]
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v2
      
      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform plan
        id: plan
        run: terraform plan

      - name: Terraform apply
        id: apply
        run: terraform apply --auto-approve


#name: GitHub Actions Demo
#run-name: ${{ github.actor }} is testing out GitHub Actions
#on: [push]
#jobs:
#  Explore-GitHub-Actions:
#    runs-on: [self-hosted]
#    steps:
#      - run: python3 --version
#      - run: gcloud -v
#      - run: terraform -v
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - run: kubectl version
#      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
#      - name: List files in the repository
#        run: |
#          ls ${{ github.workspace }}
#      - run: echo "🍏 This job's status is ${{ job.status }}."
